#!/usr/bin/env python
'''
Autogenerated code using webarya.py
Original Object Document Input:
{"totalCount":"1","imdata":[{"fvSubnet":{"attributes":{"ctrl":"","descr":"","dn":"uni/tn-Heroes/BD-Hero_Land/subnet-[10.1.120.1/22]","ip":"10.1.120.1/22","name":"","preferred":"no","scope":"public","virtual":"no"}}}]}
'''

# list of packages that should be imported for this code to work
import cobra.mit.access
import cobra.mit.request
import cobra.mit.session
import cobra.model.fv
import cobra.model.pol
from cobra.internal.codec.xmlcodec import toXMLStr

# log into an APIC and create a directory object
ls = cobra.mit.session.LoginSession('https://apic', 'admin', 'password')
md = cobra.mit.access.MoDirectory(ls)
md.login()

# the top level object on which operations will be made
polUni = cobra.model.pol.Uni('')
fvTenant = cobra.model.fv.Tenant(polUni, 'Heroes')
fvBD = cobra.model.fv.BD(fvTenant, 'Hero_Land')

# build the request using cobra syntax
fvSubnet = cobra.model.fv.Subnet(fvBD, name=u'', descr=u'', ctrl=u'', ip=u'10.1.124.1/22', preferred=u'no', virtual=u'no')


# commit the generated code to APIC
print toXMLStr(fvBD)
c = cobra.mit.request.ConfigRequest()
c.addMo(fvBD)
md.commit(c)
