#!/usr/bin/env python
'''
Autogenerated code using arya
Original Object Document Input: 
{"fvTenant":{"attributes":{"dn":"uni/tn-Heroes","name":"Heroes","rn":"tn-Heroes","status":"created"},"children":[{"fvCtx":{"attributes":{"name": "Heroes_Only"}}}]}} 
'''

# list of packages that should be imported for this code to work
import cobra.mit.access
import cobra.mit.request
import cobra.mit.session
import cobra.model.fv
import cobra.model.pol
from cobra.internal.codec.xmlcodec import toXMLStr

# log into an APIC and create a directory object
ls = cobra.mit.session.LoginSession('https://apic', 'admin', 'password')
md = cobra.mit.access.MoDirectory(ls)
md.login()

# the top level object on which operations will be made
topMo = cobra.model.pol.Uni('')


# build the request using cobra syntax
fvTenant = cobra.model.fv.Tenant(topMo, name=u'Villains')
fvCtx = cobra.model.fv.Ctx(fvTenant, name=u'Villains_Only')


# commit the generated code to APIC
print toXMLStr(topMo)
c = cobra.mit.request.ConfigRequest()
c.addMo(fvTenant)
md.commit(c)
