#!/bin/sh

pydoc -w appnope
pydoc -w autonetkit
pydoc -w backports-abc
pydoc -w backports.shutil-get-terminal-size
pydoc -w backports.ssl-match-hostname
pydoc -w certifi
pydoc -w cffi
pydoc -w configobj
pydoc -w crochet
pydoc -w cryptography
pydoc -w decorator
pydoc -w Django
pydoc -w django-debug-toolbar
pydoc -w django-filter
pydoc -w django-rest-swagger
pydoc -w django-tables2
pydoc -w djangorestframework
pydoc -w enum34
pydoc -w Exscript
pydoc -w funcsigs
pydoc -w gnureadline
pydoc -w graphviz
pydoc -w gtextfsm
pydoc -w gunicorn
pydoc -w idna
pydoc -w ipaddress
pydoc -w IPy
pydoc -w ipython
pydoc -w ipython-genutils
pydoc -w lxml
pydoc -w Mako
pydoc -w Markdown
pydoc -w MarkupSafe
pydoc -w meld3
pydoc -w mock
pydoc -w natsort
pydoc -w ncclient
pydoc -w netaddr
pydoc -w netmiko
pydoc -w networkx
pydoc -w paramiko
pydoc -w pathlib2
pydoc -w pbr
pydoc -w pexpect
pydoc -w pickleshare
pydoc -w pip
pydoc -w psycopg2
pydoc -w PTable
pydoc -w ptyprocess
pydoc -w py-gfm
pydoc -w pyasn1
pydoc -w pycparser
pydoc -w pycrypto
pydoc -w pymongo
pydoc -w pyparsing
pydoc -w pytz
pydoc -w PyYAML
pydoc -w redis
pydoc -w scp
pydoc -w setuptools
pydoc -w simplegeneric
pydoc -w SimpleParse
pydoc -w singledispatch
pydoc -w six
pydoc -w sqlparse
pydoc -w tornado
pydoc -w traitlets
pydoc -w trigger
pydoc -w Twisted
pydoc -w wheel
pydoc -w xmltodict
pydoc -w zope.interface
